import{a as y,S as L,i as l}from"./assets/vendor-DXaqCXe3.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function i(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=i(t);fetch(t.href,o)}})();const v="https://pixabay.com/api/",w="49405379-236235770e28cb9bd374c0ae0",u=async(e,s=1)=>{var a,t;const i={key:w,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:s};try{return(await y.get(v,{params:i})).data}catch(o){throw new Error(((t=(a=o.response)==null?void 0:a.data)==null?void 0:t.message)||"Failed to fetch images")}},T=({largeImageURL:e,webformatURL:s,tags:i,likes:a,views:t,comments:o,downloads:n})=>`
    <li class="gallery-item">
      <a href="${e}">
        <img src="${s}" alt="${i}">
        <div class="info">
          <div><p>Likes:</p> ${a}</div>
          <div><p>Views:</p> ${t}</div>
          <div><p>Comments:</p> ${o}</div>
          <div><p>Downloads:</p> ${n}</div>
        </div>
      </a>
    </li>
  `,p=(e,s,i=!1)=>{const a=e.map(o=>T(o)).join("");i?s.insertAdjacentHTML("beforeend",a):s.innerHTML=a,new L(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250}).refresh()},m=e=>{e.classList.remove("hidden")},f=e=>{e.classList.add("hidden")},b=e=>{e.innerHTML=""},r={form:document.querySelector(".form"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),loadMoreBtn:document.querySelector(".load-more"),scrollToTopBtn:document.querySelector(".scroll-to-top")};let d="",c=1,h=0;r.form.addEventListener("submit",B);r.loadMoreBtn.addEventListener("click",S);r.scrollToTopBtn.addEventListener("click",q);window.addEventListener("scroll",E);async function B(e){if(e.preventDefault(),d=e.target.elements["search-text"].value.trim(),c=1,!d){l.error({title:"Error",message:"Input cannot be empty!",color:"#ef4040",position:"topRight"});return}m(r.loader),r.loadMoreBtn.classList.add("hidden"),b(r.gallery);try{const s=await u(d,c);if(h=s.totalHits,s.hits.length===0){l.warning({title:"Caution",message:"Sorry, there are no images matching your search query. Please try again!",color:"#ffa000",position:"topRight"});return}p(s.hits,r.gallery),g()}catch(s){l.error({message:s.message,color:"#ef4040",position:"topRight"})}finally{f(r.loader)}}async function S(){c+=1,m(r.loader),r.loadMoreBtn.classList.add("hidden");try{const e=await u(d,c);p(e.hits,r.gallery,!0),g(),M()}catch(e){l.error({message:e.message,color:"#ef4040",position:"topRight"})}finally{f(r.loader)}}function g(){const e=Math.ceil(h/15);c<e?r.loadMoreBtn.classList.remove("hidden"):(r.loadMoreBtn.classList.add("hidden"),l.info({message:"We're sorry, but you've reached the end of search results.",color:"#09f",position:"topRight"}))}function M(){const e=r.gallery.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}function q(){window.scrollTo({top:0,behavior:"smooth"})}function E(){window.scrollY>300?r.scrollToTopBtn.classList.remove("hidden"):r.scrollToTopBtn.classList.add("hidden")}
//# sourceMappingURL=index.js.map
